#!/bin/bash

#$ -pe singlenode 8

#$ -l long

#$ -A r_ashwin
#$ -l h_rt=100008:00:00


#$ -N sml2D9
#$ -o sml2D.out
#$ -e sml2D.err
#$ -j y

#$ -V
#$ -cwd

# export MPICH2_ROOT=/opt/mpich2-1.0.8/
export PATH=$MPICH2_ROOT/bin:$PATH
export MPD_CON_EXT="sge_$JOB_ID.$TASK_ID"

echo "Got $NSLOTS slots."
# The order of arguments is important. First global, then local options.
cat $TMPDIR/machines

/home/r_ashwin/OpenFOAM/ThirdParty-2.3.0/platforms/linux64Gcc/openmpi-1.6.5/bin/mpirun -n 8 plicIsoThermTransLLEFlowFoam -parallel >& logsml2D
